### ISSUE TITLE
Unable to build otel collector

### ISSUE THREAD

**Issue by miyunari** [os-observability/redhat-opentelemetry-collector#38]
Hey, when I run `make build` I see the following error message:

```bash
go: downloading github.com/openshift/api v3.9.0+incompatible
../../../../golang_workspace/pkg/mod/github.com/openshift/client-go@v0.0.0-20210521082421-73d9475a9142/quota/clientset/versioned/typed/quota/v1/appliedclusterresourcequota.go:9:2: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.0
```
Any idea how to solve this?

Commit: 15b6bfffcb810da93b644acc60cbbdbf15ec8a57

**Comment by iblancasa** [comment]
That version is not correct. Can you replace it by `v0.0.0-20240124164020-e2ce40831f2e`?

**Comment by miyunari** [comment]
@iblancasa how can I replace the version? :)

**Comment by frzifus** [comment]
@iblancasa @miyunari As long as you want the same build, it probably makes no sense to replace the dependency. Its set in the `go.mod` file.
https://github.com/os-observability/redhat-opentelemetry-collector/blob/15b6bfffcb810da93b644acc60cbbdbf15ec8a57/_build/go.mod#L201
Presumably the `v3.9.0` tag no longer exists in the original repository.

What surprises me is that it works for me locally even after clearing the cache (`go clean -modcache`).

To test this, I started a fresh container and the same error appeared there. Checking `GONOPROXY` and `GOPROXY` solved the mystery.
```bash
go env GONOPROXY GOPROXY
```
Output ("my-machine", "fresh container"):
```diff
- https://proxy.golang.org,direct
+ direct
```

@miyunari try to run this first:
```bash
export GOPROXY=https://proxy.golang.org,direct
```

**Comment by miyunari** [comment]
That worked :smiley:
